Several minor enhancements and fixes
redhat-cop/automate-jcliff pull request #15
Opened 2019-07-16 09:39 UTC by rpelisse

2019-07-17 07:44 UTC, rpelisse commented
@sabre1041 FYI, I need the last commit (adding minimum tasks/main.yml) to be merged for the tutorial.

2019-07-17 17:25 UTC, sabre1041 requested changes
@rpelisse Added 1 comment

2019-07-17 17:25 UTC, sabre1041 commented on tasks/main.yml
> +---
@rpelisse this hardcodes it to a linux machine. I would add a condition to ensure you are running on a linux machine

2019-07-18 07:40 UTC, rpelisse commented
@sabre1041 can we disable (or limit to warning) the yamlint stuff ? right now this PR is blocked because some license file is missing. I don't want to add a license file without some serious discussion about it first. And I don't have a lot of time to work on this before Monday...

2019-07-19 06:45 UTC, sabre1041 commented
Will discuss license at a later date

2019-07-19 06:45 UTC, merged